name: Snyk IaC Test

on:
  pull_request:
    branches:
      - tes

jobs:
  snyk_iac_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk
      
      - name: Authenticate Snyk CLI
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      
      # - name: Generate JSON of Snyk report
      #   run: snyk iac test --json-file-output=snyk_iac_results.json
      #   continue-on-error: true
      
      # - name: Upload Snyk IaC JSON report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: snyk_iac_results
      #     path: snyk_iac_results.json

      - name: Run Snyk IaC test
        run: |
          snyk iac test --severity-threshold=critical
          snyk iac test --severity-threshold=high

